name: publish-site

on:
  push:
    branches:
      - main
    paths:
      - alfredo.cedeno.me/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies and build
        run: |
          set -e
          yarn --cwd ./alfredo.cedeno.me install --frozen-lockfile
          yarn --cwd ./alfredo.cedeno.me/ build

      - name: Deploy to GitHub Pages Docusaurus
        uses: redkubes/docusaurus-deploy-action@latest
        with:
          source-folder: alfredo.cedeno.me 
          git-user: ajcborges 
          git-password: ${{ secrets.GITHUB_TOKEN }} 
          deployment-branch: gh-pages
