name: test-site

on:
  pull_request:
    branches:
      - main
    paths:
      - alfredo.cedeno.me/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install
        run: |
          yarn --cwd ./alfredo.cedeno.me/ install
      - name: Build
        run: |
          yarn --cwd ./alfredo.cedeno.me/ build
